document.addEventListener("DOMContentLoaded", () => {
  const wordPairs = {
    profound: "superficial",
    purposeful: "accidental",
    accurate: "inaccurate",
    minor: "major",
    "left-wing": "right-wing",
    underestimate: "overestimate",
    atheist: "believer",
    "attack (noun)": "defence",
    marriage: "divorce",
    ordinary: "extraordinary",
    extrovert: "introvert",
    ancient: "contemporary",
    encourage: "discourage",
    encrypt: "decrypt",
    "even number": "odd number",
    czoło: "forehead",
    pacha: "armpit",
    paznokieć: "nail",
    ramię: "arm",
    kciuk: "thumb",
    żołądek: "stomach",
    kostka: "ankle",
    nadgarstek: "wrist",
    skóra: "skin",
    wargi: "lips",
    wąsy: "moustache",
    język: "tongue",
    łokieć: "elbow",
    "środkowy palec": "middle finger",
    "palec serdeczny": "ring finger",
    policzek: "cheek",
    pierś: "breast",
    mózg: "brain",
    pępek: "navel/belly button",
    ciało: "body",
    "felga aluminiowa": "alloy wheel",
    "tylna szyba": "back window",
    "maska samochodu": "bonnet",
    bagażnik: "boot/trunk",
    zderzak: "bumper",
    "drzwi samochodu": "car door",
    "pokrywa bagażnika": "decklid",
    klamka: "door handle",
    zamek: "door lock",
    błotnik: "fender/wing",
    "grill, maskownica": "grille",
    klakson: "horn",
    kołpak: "hubcap",
    "tablica rejestracyjna": "licence plate/license plate/number plate",
    chlapacz: "mud flap/splash guard",
    "lusterko wsteczne": "rearview mirror",
    felga: "rim",
    "lusterko boczne": "side mirror/wing mirror",
    "boczna szyba": "side window",
    "lusterko boczne": "side-view mirror/side-view mirror",
    spoiler: "spoiler",
    szyberdach: "sunroof",
    koło: "wheel",
    szyba: "window",
    "przednia szyba": "windscreen/windshield",
    "wycieraczki samochodowe": "windscreen wipers/windshield wipers",
    wiek: "age",
    narodziny: "birth",
    "data urodzenia": "date of birth",
    obywatel: "citizen",
    rozwiedziony: "divorced",
    kobieta: "female",
    imię: "first name",
    "zawód, praca": "profession",
    mężczyzna: "male",
    "stan cywilny": "marital status",
    "żonaty, zamężna": "married",
    narodowość: "nationality",
    zawód: "occupation",
    "dane osobowe": "personal details",
    płeć: "sex",
    "stanu wolnego": "single",
    nazwisko: "surname",
    wdowa: "widow",
    wdowiec: "widower",
    "miejsce urodzenia": "place of birth",
    "poręcz, balustrada": "banister",
    "płytki łazienkowe": "bathroom tiles",
    pościel: "bedding",
    "szafa wnękowa": "built-in wardrobe",
    "łóżko piętrowe": "bunk beds",
    komoda: "chest of drawers",
    "poduszka (dekoracyjna)": "cushion",
    biurko: "desk",
    "gablota, przeszklona szafka": "display cabinet",
    "dzwonek do drzwi": "doorbell",
    wycieraczka: "doormat",
    kominek: "fireplace",
    "zdjęcie oprawione w ramkę": "framed photograph",
    "w pełni wyposażony": "fully-fitted",
    "przeszkolny regał na książki, biblioteczka": "glass-fronted bookcase",
    "zagar szafkowy": "grandfather clock",
    "bojler podgrzewający wodę": "hot water heater",
    "sprzęt AGD": "household appliances",
    "zlew kuchenny": "kitchen sink",
    bibelot: "knick-knack",
    "robiony na zamówienie": "made to order",
    "półka nad kominkiem": "mantelpiece",
    "ozdoba, bibelot": "ornament",
    parkiet: "parquet",
    "perski dywan": "persian rug",
    "instalacja wodno-kanalizacyjna": "plumbing",
    "roślina doniczkowa": "potted plant",
    "grzejnik, kaloryfer": "radiator",
    "słuchawka (od telefonu)": "receiver",
    "fotel bujany": "rocking chair",
    rolety: "roller blinds",
    "woda bieżąca": "running water",
    "taboret, stołek": "stool",
    "krzesło obrotowe": "swivel chair",
    "krzesła tapicerowane": "upholstered chairs",
    żaluzje: "venetian blinds",
    tapeta: "wallpaper",
    parapet: "windowsill",
    "drewniana podłoga": "wooden floor",
    okiennice: "shutters",
    "podłączyć prąd": "connect electricity",
    "demontować, rozkładać na części": "dismantle",
    "zetrzeć kurz z mebli": "dust the furniture",
    naprawiać: "repair/fix",
    "instalować, montować": "install",
    wnętrze: "interior",
    długość: "length",
    "konserwacja, utrzymanie": "maintenance",
    "naprawiać cieknący kran": "mend the dripping tap",
    "kosić trawnik": "mow the lawn",
    "naoliwić zawiasy": "oil the hinges",
    "pomalować coś": "paint",
    tapetować: "paper/wallpaper",
    "remontować, odnawiać": "redecorate",
    remont: "redecoration",
    wymieniać: "replace",
    "siła, wytrzymałość": "strength",
    "wytrzymać ciężar dachu": "support the weight of the roof",
    "odkurzyć podłogę": "sweep the floor",
    "dokręcić śrubę": "tighten the screw",
    "kłaść kafelki": "tile",
    "zasunąć zatrzask u drzwi": "bolt the door",
    "w budowie": "under construction",
    "odkręcić (śrubę)": "unscrew",
    "zetrzeć pyłek kurzu": "wipe a speck of dust",
    "mieszkania w rozsądnej cenie": "affordable housing",
    kaucja: "deposit",
    "pośrednik, agent sprzedaży nieruchomości": "estate agent",
    eksmitować: "evict",
    eksmisja: "eviction",
    "właściciel domu, mieszkania": "householder",
    "właściciel domu": "landlord",
    "hipoteka, kredyt hipoteczny": "mortgage",
    "brak spłaty kredytu": "non-payment of the mortgage",
    "płacić czynsz": "pay the rent",
    nieruchomość: "real estate",
    "przejąć na własność": "repossess",
    "najem, dzierżawa": "tenancy",
    lokator: "tenant",
    "do wynajęcia": "to let",
    wanna: "bath/tub",
    "waga łazienkowa": "bathroom scales",
    kafelki: "tiles",
    bidet: "bidet",
    "kosz na brudną bieliznę": "laundry basket",
    apteczka: "medicine cabinet",
    lustro: "mirror",
    "szafka łazienkowa z lustrem": "mirrored bathroom cabinet",
    "kabina prysznicowa": "shower cubicle",
    mydło: "soap",
    mydelniczka: "soap dish",
    "dozownik do mydła": "soap dispenser",
    kran: "tap",
    ubikacja: "toilet",
    "muszla klozetowa": "toilet bowl",
    "szczotka do ubikacji": "toilet brush",
    "klapa od sedesu": "toilet lid",
    "papier toaletowy": "toilet paper",
    "deska klozetowa": "toilet seat",
    "uchwyt na papier toaletowy": "toilet roll holder",
    "ręcznik kąpielowy": "bath towel",
    "ręcznik do rąk": "hand towel",
    "wieszak na ręczniki": "towel rail",
    umywalka: "washbasin",
    "płyn do kąpieli": "bubble bath",
    "łóżko piętrowe": "bunk bed",
    "łóżko polowe": "camp bed",
    "łóżko małżeńskie": "double bed",
    "łóżko jednoosobowe": "single bed",
    "narzuta na łóżko": "bedspread",
    prześcieradło: "sheet",
    "rama łóżka": "bedstead",
    kołdra: "duvet/quilt",
    koc: "blanket",
    poduszka: "pillow",
    "lampka nocna": "bedside lamp",
    dywanik: "rug/bedside rug",
    "szafa ubraniowa": "wardrobe",
    toaletka: "dressing table",
    "szafka nocna": "bedside table",
    kaskader: "stuntman",
    "rola wiodąca": "leading role",
    "próba generalna": "dress rehearsal",
    "sztuki piękne": "fine arts",
    rozdział: "chapter",
    "napisy do filmu": "subtitles",
    arydzieło: "masterpiece",
    "podróbka, falsyfikat": "fake",
    "wierszyk dla dzieci": "nursery rhyme",
    "martwa natura": "still life",
    "sławna osoba": "celebrity",
    "mól książkowy": "bookworm",
    "komedia sytuacyjna": "sitcom",
    transmitować: "broadcast",
    bilter: "usher",
    "mieszkańcy miasta": "city dwellers",
    "przyjemnie usytuowany": "pleasantly located",
    "koszt życia, utrzymania": "cost of living",
    "śródmieście, centrum": "downtown",
    "osiedle mieszkaniowe": "housing estate",
    mieszkaniec: "resident",
    odosobniony: "isolated",
    "wścibscy sąsiedzi": "nosy neighbours",
    "peryferie miasta": "outskirts",
    "obszar wydzielony dla ruchu pieszego": "pedestrian precinct",
    "dzielnica mieszkaniowa": "residential area",
    przedmieście: "suburb",
    podmiejski: "suburban",
    "w pobliżu czegoś": "within easy reach",
    "wprowadzić się": "move in",
    strych: "loft",
    ganek: "porch",
    parapet: "windowsill",
    parking: "car park",
    drabina: "ladder",
    zakwaterowanie: "accomodation",
    szopa: "shed",
    wycieraczka: "doormat",
    przedmieścia: "suburbs",
    tapeta: "wallpaper",
    klimatyzacja: "air conditioning",
    domofon: "entryphone",
    zasłona: "curtain",
    dachówka: "tile",
    "bieżąca woda": "running water",
    żaluzja: "blind",
    "dzwonek do drzwi": "doorbell",
    "wieżowiec, drapacz chmur": "skyscraper",
    umeblowany: "furnished",
    "klatka schodowa": "staircase",
    "las deszczowy": "rain forest",
    "kwaśny deszcz": "acid rain",
    "globalne ocieplenie": "global warming",
    "wycinka lasów": "deforestation",
    recykling: "recycling",
    zanieczyszczenie: "pollution",
    "oczyszczalnia ścieków": "sewage plant",
    nawozy: "fertilisers",
    "benyzna bezołowiowa": "unleaded petrol",
    "efekt cieplarniany": "greenhouse effect",
    wymarły: "extinct",
    "dzika przyroda": "wildlife",
    "zagrożone gatunki": "endangered species",
    spaliny: "fumes",
    skażony: "contaminated",
    przestronny: "spacious",
    pusty: "bare",
    zagracony: "cluttered",
    przytulny: "cosy",
    "wystrój wnętrza": "decor",
    "zaprojektowany przez": "designed by",
    "w opłakanym stanie": "dilapidated",
    obskurny: "dingy",
    "z przeciągami": "draughty",
    "robiący wrażenie, imponujący": "impressive",
    półpiętro: "landing",
    minimalistyczny: "minimalist",
    "schludny, czysty": "neat and tidy",
    "uroczy, o staroświeckim wdzięku": "quaint",
    zaniedbany: "shabby",
    "dźwiękoszczelny, wyciszony": "soundproof",
    "skąpo urządzony": "sparsely decorated",
    "stylowy, elegancki": "stylish",
    nowoczesny: "ultra-modern",
    umeblowany: "furnished",
    limonka: "lime",
    morela: "apricot",
    malina: "raspberry",
    "czarna porzeczka": "blackcurrant",
    burak: "beet",
    koperek: "dill",
    szczypior: "chives",
    dynia: "pumpkin",
    bakłażan: "aubergine",
    cukinia: "courgette",
    groszek: "green beans/peas",
    por: "leek",
    rzodkiewka: "radish",
    "słodka kukurydza": "sweetcorn",
    pietruszka: "parsley",
    "żądny przygód, śmiały": "adventurous",
    gaduła: "chatterbox",
    radosny: "cheerful",
    pogodny: "good-natured",
    sprytny: "clever",
    zarozumiały: "conceited",
    okrutny: "cruel",
    nieciekawy: "dull",
    nudny: "boring",
    otwarty: "open",
    towarzyski: "outgoing",
    przyjazny: "friendly",
    nieprzyjazny: "unfriendly",
    nieuprzejmy: "impolite",
    nietaktowny: "tactless",
    niezależny: "independent",
    "niepewny siebie": "insecure",
    nieodpowiedzialny: "irresponsible",
    "łatwo wpadający w gniew": "bad-tempered",
    sprawiedliwy: "just/fair",
    uczciwy: "fair/honest",
    bezstronny: "impartial",
    uprzejmy: "kind",
    pomocny: "helpful",
    "pełen życia": "lively",
    "robić wrażenie": "make an impression",
    dojrzały: "mature",
    skąpy: "mean",
    "nieporządny, bałaganiarski": "messy",
    skromny: "modest",
    ograniczony: "narrow-minded",
    nietolerancyjny: "intolerant",
    okropny: "nasty",
    niemiły: "unpleasant",
    sympatyczny: "lovable",
    posłuszny: "obedient",
    osobowość: "personality",
    uprzejmy: "polite",
    taktowny: "tactful",
    "dobrze ułożony": "well-mannered",
    cichy: "quiet",
    "zamknięty w sobie": "reserved",
    samolubny: "selfish",
    egocentryczny: "self-centred",
    "poczucie humoru": "sense of humour",
    towarzyski: "sociable",
    surowy: "strict",
    uparty: "stubborn",
    niesolidny: "unreliable",
    czysty: "tidy",
    "terminal pasażerski na lotnisku": "airport terminal",
    "karta pokładowa": "boarding pass",
    łódź: "boat",
    "przystanek autobusowy": "bus stop",
    odwołany: "cancelled",
    wagon: "carriage",
    "odprawa biletowo-bagażowa": "check-in",
    autokar: "coach",
    przedział: "compartment",
    opóźniony: "delayed",
    "hala odlotów": "departure lounge",
    "opłata za przejazd": "fare",
    "terminal promowy": "ferry terminal",
    "wyjście ( do samolotu)": "gate",
    ciężarówka: "lorry",
    "półka na bagaż": "luggage rack",
    autostrada: "motorway/highway",
    pasażer: "passenger",
    "kontrola paszportowa": "passport control",
    pieszy: "pedestrian",
    peron: "platform",
    kolej: "railway",
    "stacja kolejowa": "railway station",
    hulajnoga: "scooter",
    "postój taksówek": "taxi rank",
    "kasa biletowa": "ticket office",
    "korek uliczny": "traffic jam",
    "sygnalizacja świetlna": "traffic lights",
    tramwaj: "tram",
    "wagon towarowy": "truck",
    metro: "underground",
    "stacja metra": "underground station",
    furgonetka: "van",
    poczekalnia: "waiting room",
    Tir: "articulated lorry",
    "punkt odbioru bagażu": "baggage reclaim",
    "kolejka linowa": "cable car",
    przeprawa: "crossing",
    "statek wycieczkowy": "cruise liner",
    pokład: "deck",
    "autobus piętrowy": "double-decker",
    "samochód z napędem na cztery koła": "four-by-four",
    "port, przystań": "harbour",
    "podróżowanie autostopem": "hitchhiking",
    "pas ruchu": "lane",
    "przejazd kolejowy": "level crossing",
    barka: "narrow boat",
    "schowek na bagaż podręczny w samolocie": "overhead locker",
    rondo: "roundabout",
    "pas startowy": "runway",
    "godziny szczytu": "rush hour",
    żaglówka: "sailing boat",
    "bilet okresowy": "season ticket",
    "wyciąg narciarski": "ski lift",
    "motorówka wyścigowa": "speedboat",
    fotoradar: "speed camera",
    "samochód sportowy": "sports car",
    "choroba lokomocyjna": "travel sickness",
    zakwaterowanie: "accommodation",
    "opłata za wstęp": "admission charge",
    "broszura reklamowa": "brochure",
    "numer kontaktowy": "contact number",
    "wydarzenia kulturalne": "cultural events",
    "godziny otwarcia": "opening times",
    "ciekawe miejsce": "place of interest",
    "parki krajobrazowe": "places of natural beauty",
    "wycieczka ze zwiedzaniem": "sightseeing tour",
    "rozkład jazdy": "timetable",
    "biuro informacji turystycznej": "tourist information office",
    "samochód kempingowy": "camper van/camper",
    "przyczepa kempingowa": "caravan",
    pensjonat: "guest house",
    "miejscowość wypoczynkowa": "holiday resort",
    "rodzina goszcząca turystę": "host family",
    schronisko: "hostel",
    "z własnym wyżywieniem": "self-catering",
    "wolne pokoje": "vacancies",
    "wczasy dla amatorów aktywnego wypoczynku": "adventure holiday",
    "wędrowka z plecakiem": "backpaking",
    "wczasy nad morzem": "beach holiday",
    katedra: "cathedral",
    "krótki wyjazd turystyczny": "city break",
    wspinaczka: "climbing",
    "rejs wycieczkowy": "cruise",
    kolarstwo: "cycling",
    opuszczony: "deserted",
    wycieczka: "excursion",
    lot: "flight",
    "kierownik pociągu": "guard",
    "piesza wycieczka": "hiking",
    "rezydentka biura podróży": "holiday repsentative",
    podróż: "journey",
    ulotka: "leaflet",
    "rezerwat przyrody": "nature reserve",
    "wczasy zorganizowane": "package holiday",
    "polowanie na pamiątki": "souvenir hunting",
    "mleczko do opalania": "suntan lotion",
    opalanie: "sunbathing",
    "park rozrywki": "theme park",
    "kontroler biletów": "ticket inspector",
    "wycieczka objazdowa": "tour",
    przewodnik: "tour guide",
    wędrowka: "trekking",
    "krótka wycieczka": "trip",
    rejs: "voyage",
    starożytny: "ancient",
    "wycieczka statkiem": "boat trip",
    "widok zapierający dech w piersiach": "breathtaking view",
    niskobudżetowy: "budget",
    "bezpośredni lot": "direct flight",
    "wycieczka całodniowa": "full-day excursion",
    "pobyt na luksusowym kempingu": "glamping",
    "wycieczka z przewodnikiem": "guided tour",
    "wycieczka półdniowa": "half-day excursion",
    wczasowicz: "holidaymaker",
    "długi lot": "long-haul flight",
    "piaszczysta plaża": "sandy beach",
    "strome urwisko": "sheer cliff",
    "wakacje spędzone w domu": "staycation",
    okolica: "surrounding area",
    "emocjonująca przejażdżka": "thrilling ride",
    karetka: "ambulance",
    "nagły wypadek": "emergency",
    "koło ratunkowe": "lifebelt",
    "szalupa ratunkowa": "lifeboat",
    "kamizelka ratunkowa": "lifejacket",
    "ćwiczenia przeciwpożarowe": "fire drill",
    bazylia: "basil",
    mięta: "mint",
    pietruszka: "parsley",
    sezam: "sesame",
    musztarda: "mustard",
    oregano: "oregano",
    rozmaryn: "rosemary",
    tymianek: "thyme",
    cynamon: "cinnamon",
    kolendra: "coriander",
    imbir: "ginger",
    majeranek: "marjoram",
    "gałka muszkatołowa": "nutmeg",
    papryka: "paprika",
    wanilia: "vanilla",
    anyż: "anise",
    "liść laurowy": "bay leaf",
    "gorczyca czarna": "black mustard",
    kminek: "caraway",
    cardamon: "cardamom",
    kocimiętka: "catnip",
    goździki: "clove",
    "kmin rzymski": "cumin",
    curry: "curry powder",
    "siemię lniane": "flaxseeds",
    żeńszeń: "ginseng",
    jałowiec: "juniper",
    "trawa cytrynowa": "lemon grass",
    lubczyk: "lovage",
    "mięta pieprzowa": "peppermint",
    szafran: "saffron",
    szałwia: "sage",
    szczaw: "sorrel",
    estragon: "tarragon",
    kurkuma: "turmeric",
    rodzeństwo: "siblings",
    przodek: "ancestor",
    chrzestni: "godparents",
    chrześniak: "godson",
    "przybrane dziecko": "foster child",
    "przyrodnia siostra": "half-sister",
    potomstwo: "offspring",
    znajomy: "acquaintance",
    konkubina: "concubine",
    parapetówka: "house-warming party",
    "wieczór panieński": "hen party",
    "wieczór kawalerski": "stag night",
    "rocznica ślubu": "wedding anniversary",
    rodak: "compatriot",
    "najbliższy krewny": "next of kin",
  };

  let currentKey = "";

  function loadRandomWord() {
    const keys = Object.keys(wordPairs);
    currentKey = keys[Math.floor(Math.random() * keys.length)];
    document.getElementById("question").textContent = currentKey;
    document.getElementById("answer").value = "";
    document.getElementById("result").textContent = "";
  }

  document.getElementById("check").addEventListener("click", () => {
    const userAnswer = document.getElementById("answer").value.trim();
    const correctAnswer = wordPairs[currentKey];
    if (userAnswer.toLowerCase() === correctAnswer.toLowerCase()) {
      document.getElementById("result").textContent = "Correct!";
      document.getElementById("result").className = "correct";
    } else {
      document.getElementById(
        "result"
      ).textContent = `Incorrect! The correct answer is ${correctAnswer}.`;
      document.getElementById("result").className = "incorrect";
    }
  });

  document.getElementById("next").addEventListener("click", loadRandomWord);

  loadRandomWord(); // Initial load
});
